[build]
builder = "dockerfile"

[deploy]
startCommand = "/usr/local/tomcat/bin/start-app.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
